# Generated by Django 4.0.6 on 2023-01-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_store_alter_ratings_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='corr',
            new_name='name',
        ),
    ]
