# Generated by Django 4.0.6 on 2023-01-19 14:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recomeal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100000), blank=True, default=[], size=None),
        ),
    ]
