# Generated by Django 4.0.6 on 2023-01-19 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_recomeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recomeal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100000), blank=True, default='a', size=None),
        ),
    ]
