# Generated by Django 4.0.6 on 2023-01-23 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_physic_duration_alter_physic_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physic',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='physic',
            name='height',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='physic',
            name='weight',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='physic',
            name='weight_goal',
            field=models.IntegerField(default=0),
        ),
    ]
