# Generated by Django 4.0.6 on 2023-01-23 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_physic_duration_alter_physic_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physic',
            name='height',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=list), size=None),
        ),
        migrations.AlterField(
            model_name='physic',
            name='weight',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=list), size=None),
        ),
    ]
