# Generated by Django 4.0.6 on 2023-01-23 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_physic_height_alter_physic_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='physic',
            name='height_timestamp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='physic',
            name='weight_timestamp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None),
        ),
    ]
