# Generated by Django 4.0.6 on 2023-01-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_physic_height_alter_physic_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
    ]
